#!/usr/bin/env python3

import sys
import os

def factorize(n):
    factors = []
    for i in range(2, int(n**0.5) + 1):
        while n % i == 0:
            factors.append(i)
            n //= i
    if n > 1:
        factors.append(n)
    return factors

def main():
    if len(sys.argv) != 2:
        print("Usage: factors <file>")
        return

    input_file = sys.argv[1]

    # Get the absolute path of the script
    script_dir = os.path.dirname(os.path.abspath(__file__))
    # Combine it with the input file name
    input_path = os.path.join(script_dir, input_file)

    with open(input_path, 'r') as file:
        for line in file:
            n = int(line.strip())
            factors = factorize(n)
            # Output factorization
            print(f"{n}={factors[0]}*{factors[-1]}")

if __name__ == "__main__":
    main()

